### PR TITLE
feature/student-mentors-name

### PR DESCRIPTION
**Pull request by markanator**
What kind of change does this PR introduce?
Feature.

- mentee details modal fetches assigned mentor by Id
- mentee details modal displays mentor's full name

### CODE REVIEW

**Comment by markanator** [comment]
[As a Headmaster, I would like to see if a given student has a specified mentor on their details modal.](https://trello.com/c/UmyEB8ik/44-as-a-headmaster-i-would-like-to-see-if-a-given-student-has-a-specified-mentor-on-their-details-modal)

**Review by josesustaita — APPROVED** [review]
Great job, bug is now fixed. The mentor data is being retrieved so we now know which mentor is assigned to a mentee

**Review by Cireimu — APPROVED** [review]
Looks good, works as intended, and PR is overall brief and concise.

**Comment by Cireimu** [comment]
PR is good to go, just need to pull the latest changes from `main` before we can merge.

**Pull request merged**
